version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/app  # Bind mount the current directory to /app in the container
    ports:
      - "8000:8000"
    command: python django_web_app/manage.py runserver 0.0.0.0:8000

